server:
  port: 8090
spring:
  application:
    name: spring-data-redis
  radis:
    host: localhost
    port: 6379
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url:  jdbc:mysql://localhost:3306/codeforsolution
#    username: root
#    password: mysql
#    driver-class-name:  com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled:  true
