spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url:  jdbc:mysql://localhost:3306/codeforsolution
    username: root
    password: mysql
    driver-class-name:  com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled:  true
