spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri:  lb://user-service
            predicates:
              - Path=/users/**
          - id: product-service
            uri: lb://product-service
            predicates:
            - Path=/products/**

eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8787



